Fix trades pagination
signum-network/signum-node pull request #699
Opened 2022-11-24 13:50 UTC by jjos2372

Fix for trades pagination and also sync with the current main fork.

2022-11-24 13:51 UTC, frankTheTank72 approved these changes

2022-11-25 11:08 UTC, ohager requested changes
Unfortunately, the issue persist.

2022-11-25 11:08 UTC, ohager commented on src/brs/db/sql/SqlTradeStore.java
> +    List<SortField<?>> sort = new ArrayList<>();
@jjos2372 seems that the issue persists

![image](https://user-images.githubusercontent.com/3920663/203972698-2242e055-dbb3-4730-9c60-f75b7170b000.png)


![image](https://user-images.githubusercontent.com/3920663/203972506-d330c40d-7964-4123-8e42-905f5bd05c6e.png)

2023-04-03 12:34 UTC, ohager commented
I tend to close this.... @jjos2372 ?

2023-09-20 19:05 UTC, closed without merging